#mysql
spring:
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart: #设置文件最大上传大小1GB
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    #mysql配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.xjh.springboot.pojo

server:
  port: 9000